### ISSUE TITLE
All examples in the document are not functioning properly ！！！

### ISSUE THREAD

**Issue by xuhao0521** [robert-haas/alogos#1]
bnf_text = """
<number> ::= <digit> . <digit><digit><digit>
<digit>  ::= 0
<digit>  ::= 1
<digit>  ::= 2
<digit>  ::= 3
<digit>  ::= 4
<digit>  ::= 5
<digit>  ::= 6
<digit>  ::= 7
<digit>  ::= 8
<digit>  ::= 9
"""
grammar1 = al.Grammar(bnf_text= bnf_text)

When I run the above code, the following error prompt will appear：

alogos.exceptions.GrammarError: Following nonterminals appeared on a right-hand side of a production rule but on no left-hand side:
<digit>

**Comment by robert-haas** [comment]
Thank you for reporting the issue. It seems the grammar specification can not be parsed correctly from the provided string because of a problem with newline encodings on different platforms. It suspect that it should work with a fix that is present from v0.2.1 onwards. If that is still not the case, please let me know.

**Comment by xuhao0521** [comment]
@robert-haas
Now the code can work normally on the windows platform, thanks for your timely code update. In addition, I also send you the email (xxxhhh0521@163.com).

Thank you again! Great job!

**Comment by robert-haas** [comment]
Thank you for trying the package and discovering the problem @xuhao0521. I'll close this issue since the bug appears to be fixed with the changes introduced in the transition from v0.2.0 to v0.2.1.
